//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessoriesWebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int userID { get; set; }
        public string adName { get; set; }
        public int quantity { get; set; }
    
        public virtual Ad Ad { get; set; }
        public virtual User User { get; set; }
    }
}
